### ISSUE TITLE
Deploying in Production mode

### ISSUE THREAD

**Issue by WouterStulp** [magefan/magento2-zero-downtime-deploy#1]
Hello,

We have a problem with the [Magento 2 Zero Downtime Deployment](https://magefan.com/blog/magento-2-zero-downtime-deployment) script when running in Production mode.

When we run the script the correct file are made in the pub static folder, but not in the var/prepossessed.

Is there a solution to generate the static content in the var/prepossessed folder in production mode?

**Comment by ihorvansach** [comment]
Hello @GiantHoax , thank you for your request. Can you please let us know what is your Magento version and edition?

**Comment by WouterStulp** [comment]
Hello @ihorvansach The magento version is 2.3.2 and the CE edition

**Comment by magefan** [comment]
@GiantHoax , we have tested and cannot reproduce this issue deployment process goes well. Can you please provide more details, like what is wrong with var/view_...sed files in your case?

just as a suggestion, maybe you have some file permission issues in your system?

**Comment by WouterStulp** [comment]
@magefan I think i have found the issue, when i look at the deployed files with setup:static-content:deploy i see for example the styles-m.min.css.

When i deploy the site with the script I only see the normal styles-m.css and styles-m.less

This is in the folder: var/view_preprocessed/pub/static/frontend/ThemeVendor/Theme/nl_NL/css

See the screenshot attached.
![Screenshot from 2019-11-01 11-12-35](https://user-images.githubusercontent.com/10993605/68018087-8a7a2500-fc98-11e9-8adc-a1a1ba1a0532.png)

**Comment by WouterStulp** [comment]
It had something to do with the env file. solved
